#!/bin/dash
echo "Tag: ${DOCKER_TAG}"
echo  "Name: ${IMAGE_NAME}"
phpVer=${DOCKER_TAG%_*}
nodeVer=${DOCKER_TAG#"$phpVer"}
nodeVer=${nodeVer#_}
echo "php ver: ${phpVer}"
echo "node ver: ${nodeVer}"
# docker build --build-arg PHP_VER="${configs[0]}" NODE_VER="${configs[1]}" -f $DOCKERFILE_PATH -t $IMAGE_NAME .
