version: '3.8'
#parent docker
services:
  web:
    build:
      context: ./docker-file
      dockerfile: nginx.dockerfile
    image: 'max26292/local-nginx:stable'
  app:
    image: 'max26292/local-php:8.0'
    container_name: app_fpm
    build:
      context: ./docker-file
      dockerfile: php-image.dockerfile
      args:
        PHP_VER: 8.0
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64   
  node:
    image: 'max26292/local-node-php:80.16'
    build:
      context: ./docker-file
      dockerfile: node.dockerfile
      args:
        PHP_VER: '8.0'
        NODE_VER: 16
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
  rsync:
    image: 'max26292/rsync:v1'
    build:
      context: ./docker-file
      dockerfile: rsync.dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
