version: '3.8'
#parent docker
services:
  web:
    build:
      context: ./docker-file
      dockerfile: nginx.dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: 'max26292/local-nginx:1.24'    
  app:
    image: 'max26292/local-php:${PHP_VER}'
    container_name: app_fpm
    build:
      context: ./docker-file
      dockerfile: php-image.dockerfile
      args:
        PHP_VER: ${PHP_VER}
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
          # - linux/arm64v8 
  webapp:
    image: 'max26292/local-nginx-fpm:${PHP_VER}'
    build:
      context: ./docker-file
      dockerfile: nginx-php.dockerfile    
      args:
        PHP_VER: '${PHP_VER}'
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
  node:
    image: 'local-node-php:${PHP_VER}_${NODE_VER}'
    build:
      context: ./docker-file
      dockerfile: node.dockerfile
      args:
        PHP_VER: ${PHP_VER}
        NODE_VER: ${NODE_VER}
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64 
          # - linux/arm64v8
  proxy:
    image: 'europe-west6-docker.pkg.dev/mern-app-310602/strapi/nginx-proxy'
    build:
      context: ./docker-file
      dockerfile: proxy.dockerfile
      x-bake:
        platforms:
          - linux/amd64
          # - linux/arm64
