version: '3.8'
#parent docker
services:
  web:
    build:
      context: ./docker-file
      dockerfile: nginx.dockerfile
    image: 'max26292/local-nginx:stable'
  app:
    image: 'max26292/local-php:7.4'
    container_name: app_fpm
    build:
      context: ./docker-file
      dockerfile: php-image.dockerfile
      args:
        PHP_VER: 7.4
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64   
  node:
    image: 'max26292/local-node-php:74.12'
    build:
      context: ./docker-file
      dockerfile: node.dockerfile
      args:
        PHP_VER: 7.4
        NODE_VER: 12
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
