version: '3.8'
#parent docker
services:
  redis:
    image: 'europe-west6-docker.pkg.dev/mern-app-310602/strapi/nginx-proxy'
    ports:
      - "8080:8080"
    networks:
      app-network: 
networks:
  app-network:
    name: app-network
    driver: bridge