version: '3.8'
#parent docker
services:
  web:
    build:
      context: ./docker-file
      dockerfile: nginx.dockerfile
    image: 'max26292/local-nginx:stable'
  webapp:
    image: 'max26292/local-nginx-fpm:${PHP_VER}'
    build:
      context: ./docker-file
      dockerfile: nginx-php.dockerfile    
      args:
        PHP_VER: '${PHP_VER}'
  app:
    image: 'max26292/local-php:${PHP_VER}'
    build:
      context: ./docker-file
      dockerfile: php-image.dockerfile
      args:
        PHP_VER: '${PHP_VER}'
  node:
    image: 'local-node-php:latest'
    build:
      context: ./docker-file
      dockerfile: node.dockerfile
      args:
          PHP_VER: '${PHP_VER}'
          NODE_VER: '${NODE_VER}'
networks:
  app-network:
    name: app-network
    driver: bridge