version: '3.8'
#parent docker
services:
  web:
    build:
      context: ./docker-file
      dockerfile: nginx.dockerfile
    image: 'local/nginx:stable'
  app:
    image: 'local/php:${PHP_VER}'
    container_name: app_fpm
    build:
      context: ./docker-file
      dockerfile: php-image.dockerfile
      args:
        PHP_VER: '${PHP_VER}' 
networks:
  app-network:
    name: app-network
    driver: bridge
    ipam:
      config:
        - subnet: '${IP_PREFIX}.0/16'
          gateway: '${IP_PREFIX}.1'
