version: 2.1
parameters:
  action:
    type: enum
    enum: [php81, php82,php8,node81_16,node82_16,node8_16,node81_18,node82_18,node8_18]
    default: php81
commands:
  setup:
    steps:
      - checkout
      - run:
          name: setup Qemu
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run:
          name: Create builder
          command: |
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build
jobs:
  build-php:
    machine:
      image: ubuntu-2204
      docker_layer_caching: true
    steps:
      - setup
      - run:
          name: Login to image registry
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build multiarch docker image and push
          command: |
            docker buildx bake -f build.yml app --push
workflows:
  version: 2.1
  build-php-81:
    when:
      equal: [ php81, << pipeline.parameters.action >> ]
    jobs:
      - build-php:
          context: php81
      