version: '3.8'

services:
  db:
    image: 'mysql:5.7'
    restart: unless-stopped
    tty: true
    ports:
      - '${DB_EXTERNAL_PORT}:3306'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '12345678#'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
    volumes:
      - ./dbdata-mysql:/var/lib/mysql/
      - './config/mysql/my.conf:/etc/mysql/conf.d/my.cnf'
      - './initdb/:/docker-entrypoint-initdb.d/'
    networks:
      app-network: 
  app:
    image: 'local/php:${PHP_VER}'
    environment: 
      DB_DATABASE: '${DB_DATABASE}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_HOST: '${DB_HOST}'        
    restart: unless-stopped
    volumes:
      - ${SOURCE_PATH}:/var/www/html
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db
    networks:
      app-network:
  app_ex:
    image: 'local/php:${PHP_VER}-apache'
    environment: 
      DB_DATABASE: '${DB_DATABASE}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_HOST: '${DB_HOST}'        
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
    volumes:
      - ${SOURCE_PATH}:/var/www/html
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db
    networks:
      app-network:
  web:
    image: 'local/nginx:stable'
    # restart: unless-stopped
    tty: true
    ports:
      - '${WEB_PORT}:80'
    volumes:
      - ${SOURCE_PATH}:/var/www/html
      - ./config/nginx/:/etc/nginx/templates
    environment: 
      APP_SERVICE: ${APP_SERVICE}
    depends_on: 
      - app
    networks:
      app-network:
  redis:
    image: 'redis:5.0.7'
    networks:
      app-network:
  memcached:
    image: 'memcached:alpine3.14'
    networks:
        app-network:
networks:
  app-network:
    name: ${NETWORK_NAME}
    driver: bridge
    external: true
