version: '3.8'

services:
  db:
    image: 'mysql:5.7'
    restart: unless-stopped
    tty: true
    ports:
      - '${DB_EXTERNAL_PORT}:3306'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '12345678#'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
    volumes:
      - ./dbdata-mysql:/var/lib/mysql/
      - './docker-file/config/mysql/my.conf:/etc/mysql/conf.d/my.cnf'
      - './initdb/:/docker-entrypoint-initdb.d/'
    networks:
      app-network: 
  app:
    image: 'local/php:${PHP_VER}'
    environment: 
      DB_DATABASE: '${DB_DATABASE}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_HOST: '${DB_HOST}'        
    restart: unless-stopped
    volumes:
      - ${SOURCE_PATH}:/var/www/html    
    depends_on:
      - db
    networks:
      app-network:
  web:
    image: 'local/nginx:stable'
    # restart: unless-stopped
    tty: true
    ports:
      - '81:80'
    volumes:
      - ${SOURCE_PATH}:/var/www/html
      - ./config/nginx/:/etc/nginx/templates
    environment: 
      - APP_SERVICE: ${APP_SERVICE}
    depends_on: 
      - app_fpm
    networks:
      app-network:
  redis:
    image: 'redis:5.0.7'
    networks:
      app-network: 
networks:
  app-network:
    name: app-network
    driver: bridge
    external: true
