name: Build PHP Nginx docker
run-name: ${{ github.actor }} is building PHP docker🚀
on:
  workflow_dispatch:
    inputs:
      phpVersion:
        description: Php version
        required: true
        default: "8.1"
        type: choice
        options:
          - 8.4
          - 8.3
          - 8.2
          - 8.1
          - 8.0
          - 7.4
jobs:
  build:
    runs-on: ubuntu-latest
    environment: php8
    env:
      REGISTRY_IMAGE: ${{ vars.DOCKER_USER }}/local-nginx-fpm
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4.1.0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=${{inputs.phpVersion}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "max26292/mybuilder"
          install: true
     
      -
        name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5.4.0
        with:
          context: ./docker-file
          file: ./docker-file/nginx-php.dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push=true
          build-args: |
            PHP_VER=${{inputs.phpVersion}}
      -
        name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      -
        name: Upload digest
        uses: actions/upload-artifact@v4.3.1
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
  merge:
    runs-on: ubuntu-latest
    environment: php8
    env:
      REGISTRY_IMAGE: ${{ vars.DOCKER_USER }}/local-nginx-fpm
    needs:
      - build
    steps:
      -
        name: Download digests
        uses: actions/download-artifact@v4.1.7
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "max26292/mybuilder"
          install: true
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=${{inputs.phpVersion}}
      
      -
        name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ steps.meta.outputs.tags }}