name: Build PHP-Node docker
run-name: ${{ github.actor }} is building PHP NODE 🚀
on:
  workflow_dispatch:
    inputs:
      phpVersion:
        description: Php version
        required: true
        default: "8.1"
        type: choice
        options:
          - 8.1
          - 8.0
          - 7.4
          - 8.2
      nodeVersion:
          description: node version
          required: true
          default: "16"
          type: choice
          options:
            - 16
            - 18
            - 14
jobs:
  build:
    runs-on: ubuntu-latest
    environment: php8
    env:
      REGISTRY_IMAGE: ${{ vars.DOCKER_USER }}/${{ vars.REGISTRY_NODE_NAME }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=${{inputs.phpVersion}}_${{inputs.nodeVersion}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "max26292/mybuilder"
          install: true
      -
        name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./docker-file
          file: ./docker-file/node.dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push=true
          build-args: |
            PHP_VER=${{inputs.phpVersion}}
            NODE_VER=${{inputs.nodeVersion}}
      -
        name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      -
        name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
  merge:
    runs-on: ubuntu-latest
    environment: php8
    env:
      REGISTRY_IMAGE: ${{ vars.DOCKER_USER }}/${{ vars.REGISTRY_NODE_NAME }}
    needs:
      - build
    steps:
      -
        name: Download digests
        uses: actions/download-artifact@v4
        with:
          name: digests
          path: /tmp/digests
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=${{inputs.phpVersion}}_${{inputs.nodeVersion}}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ steps.meta.outputs.tags }}
